import type { ContestEngine } from './contest';

/**
 * Schedules PCM blocks generated by ContestEngine through Web Audio.
 * Keeps 2 blocks ahead of the playback cursor for low latency and underrun safety.
 */
export class AudioScheduler {
  private context: AudioContext | null = null;
  private gain: GainNode | null = null;
  private engine: ContestEngine | null = null;
  private nextTime = 0;
  private timer: number | null = null;
  private running = false;
  readonly latencyBlocks = 2;

  async start(engine: ContestEngine, volume = 0.35) {
    if (this.running) return;
    this.engine = engine;
    this.context = new AudioContext({ sampleRate: engine.sampleRate, latencyHint: 'interactive' });
    if (this.context.state === 'suspended') await this.context.resume();
    this.gain = this.context.createGain();
    this.gain.gain.value = volume;
    this.gain.connect(this.context.destination);
    this.nextTime = this.context.currentTime + 0.08;
    this.running = true;

    const blockSeconds = engine.blockSize / engine.sampleRate;
    const scheduleAhead = () => {
      if (!this.running || !this.context || !this.engine) return;
      while (this.nextTime < this.context.currentTime + this.latencyBlocks * blockSeconds + 0.02) {
        const samples = this.engine.getAudio();
        const buffer = this.context.createBuffer(1, samples.length, this.context.sampleRate);
        buffer.getChannelData(0).set(samples);
        const source = this.context.createBufferSource();
        source.buffer = buffer;
        source.connect(this.gain!);
        source.start(this.nextTime);
        this.nextTime += blockSeconds;
      }
      this.timer = window.setTimeout(scheduleAhead, 10);
    };
    scheduleAhead();
  }

  setVolume(v: number) {
    if (this.gain && this.context) this.gain.gain.setTargetAtTime(v, this.context.currentTime, 0.01);
  }

  stop() {
    this.running = false;
    if (this.timer) window.clearTimeout(this.timer);
    this.timer = null;
    const ctx = this.context;
    this.context = null;
    this.gain = null;
    this.engine = null;
    void ctx?.close();
  }

  get isRunning() { return this.running; }
}

