import type { Qso, UserSettings } from '../types';
import { CONTESTS, type ContestId } from './contest-defs';

export interface CabrilloExportOptions {
  contest: ContestId;
  settings: UserSettings;
  qsos: Qso[];
  startedAt?: Date;
  includeInvalid?: boolean;
}

const CABRILLO_CONTESTS: Record<ContestId, string> = {
  wpx: 'CQ-WPX-CW',
  cwt: 'CWOPS-CWT',
  fd: 'ARRL-FIELD-DAY',
  naqp: 'NAQP-CW',
  hst: 'HST-CW',
  cqww: 'CQ-WW-CW',
  arrldx: 'ARRL-DX-CW',
  sst: 'K1USN-SST',
  allja: 'JARL-ALL-JA',
  acag: 'JARL-ACAG',
  iaruhf: 'IARU-HF',
  ss: 'ARRL-SS-CW',
};

function dateParts(date: Date) {
  const year = String(date.getUTCFullYear()).padStart(4, '0');
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  const hours = String(date.getUTCHours()).padStart(2, '0');
  const minutes = String(date.getUTCMinutes()).padStart(2, '0');
  return { date: `${year}-${month}-${day}`, time: `${hours}${minutes}` };
}

function normalizeRst(value: string) {
  if (/^5N[NO]?$/i.test(value)) return '599';
  return value.toUpperCase();
}

function serial(value: string) {
  const match = value.match(/\d+/);
  return match ? String(Number(match[0])) : '0';
}

function splitCheckSection(value: string) {
  const match = value.trim().match(/^(\d{2,4})\s+(.+)$/);
  return match ? { check: match[1], section: match[2].toUpperCase() } : { check: '00', section: value.toUpperCase() };
}

function qsoExchange(contest: ContestId, qso: Qso) {
  const sent = [normalizeRst(qso.exch1), qso.exch2];
  const received = [normalizeRst(qso.trueExch1 || qso.exch1), qso.trueExch2 || qso.exch2];

  if (contest === 'wpx' || contest === 'hst') {
    return [...sent, ...received];
  }

  if (contest === 'ss') {
    const sentCheck = splitCheckSection(qso.exch2);
    const recvCheck = splitCheckSection(qso.trueExch2 || qso.exch2);
    return [serial('1'), qso.exch1, sentCheck.check, sentCheck.section,
      serial('1'), qso.trueExch1 || qso.exch1, recvCheck.check, recvCheck.section];
  }

  return [...sent, ...received];
}

function line(tag: string, value = '') {
  return value ? `${tag}: ${value}` : `${tag}:`;
}

export function exportCabrillo({
  contest, settings, qsos, startedAt = new Date(), includeInvalid = false,
}: CabrilloExportOptions): string {
  const definition = CONTESTS[contest];
  const rows = qsos.filter((qso) => includeInvalid || qso.err === '   ');
  const created = startedAt.toISOString();

  const header = [
    'START-OF-LOG: 3.0',
    line('CALLSIGN', settings.call),
    line('CONTEST', CABRILLO_CONTESTS[contest]),
    line('CATEGORY-OPERATOR', 'SINGLE-OP'),
    line('CATEGORY-ASSISTED', 'NON-ASSISTED'),
    line('CATEGORY-BAND', 'ALL'),
    line('CATEGORY-MODE', 'CW'),
    line('CATEGORY-POWER', 'LOW'),
    line('CATEGORY-TRANSMITTER', 'ONE'),
    line('CLAIMED-SCORE', '0'),
    line('OPERATORS', settings.call || settings.name || 'UNKNOWN'),
    line('NAME', settings.name || 'UNKNOWN'),
    line('LOCATION', ''),
    line('CREATED-BY', `Morse Runner Web (${definition.name})`),
    line('SOAPBOX', 'Generated by a local CW training session'),
  ].filter(Boolean);

  const records = rows.map((qso) => {
    const time = new Date(startedAt.getTime() + qso.time * 1000);
    const parts = dateParts(time);
    const fields = qsoExchange(contest, qso);
    const sent = fields.slice(0, Math.floor(fields.length / 2));
    const received = fields.slice(Math.floor(fields.length / 2));
    return [
      'QSO', parts.date, parts.time, settings.call || 'UNKNOWN', ...sent, qso.call, ...received,
    ].join(' ');
  });

  return [...header, ...records, 'END-OF-LOG:', `CREATED: ${created}`, ''].join('\n');
}

export function downloadCabrillo(options: CabrilloExportOptions) {
  const content = exportCabrillo(options);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  const stamp = (options.startedAt ?? new Date()).toISOString().slice(0, 19).replace(/[:T]/g, '-');
  anchor.href = url;
  anchor.download = `morse-runner-web-${options.contest}-${stamp}.log`;
  anchor.click();
  URL.revokeObjectURL(url);
}
